[workspace]
members = ["ska_backend", "ska_frontend", "ska_migration"]
# default-members = []
resolver = "2"


[workspace.dependencies]
dotenv = "0.15.0"
axum = "0.7.3"
hyper = "1.1.0"
tokio = "1.35.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console_log = "1.0.0"
leptos = "0.5.4"
leptos_router = "0.5.4"
log = "0.4.20"
reqwest = "0.11.23"
serde = "1.0.194"
serde_json = "1.0.111"
wasm-bindgen-test = "0.3.39"
strum = "0.25.0"
strum_macros = "0.25.3"
chrono = "0.4.31"
sea-orm = "0.12.11"
sea-orm-migration = "0.12.11"
async-std = "1.12.0"
