[workspace]
members = ["ska_backend", "ska_frontend", "ska_migration"]
# default-members = []
resolver = "2"


[workspace.dependencies]
dotenv = "0.15.0"
axum = "0.7.4"
hyper = "1.2.0"
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
console_log = "1.0.0"
leptos = "0.6.8"
leptos_router = "0.6.8"
log = "0.4.21"
reqwest = "0.11.24"
serde = "1.0.197"
serde_json = "1.0.114"
wasm-bindgen-test = "0.3.41"
strum = "0.26.1"
strum_macros = "0.26.1"
chrono = "0.4.34"
sea-orm = "0.12.14"
sea-orm-migration = "0.12.14"
async-std = "1.12.0"
oauth2 = "4.4.2"
openidconnect = "3.5.0"
anyhow = "1.0.80"
futures = "0.3.30"
leptos-use = "0.10.3"
tower = "0.4.13"
tower-http = "0.5.2"
const_format = "0.2.32"
