[workspace]
members = ["ska_backend", "ska_frontend", "ska_migration"]
# default-members = []
resolver = "2"


[workspace.dependencies]
dotenv = "0.15.0"
axum = "0.7.4"
hyper = "1.1.0"
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console_log = "1.0.0"
leptos = "0.6.5"
leptos_router = "0.6.5"
log = "0.4.20"
reqwest = "0.11.24"
serde = "1.0.196"
serde_json = "1.0.113"
wasm-bindgen-test = "0.3.40"
strum = "0.26.1"
strum_macros = "0.26.1"
chrono = "0.4.33"
sea-orm = "0.12.12"
sea-orm-migration = "0.12.12"
async-std = "1.12.0"
