[tool.poetry]
name = "thapo-ska"
version = "0.1.0"
description = ""
authors = ["ThanosApostolou <thanosapostolou@outlook.com>"]
readme = "README.md"
packages = [{ include = "ska_llm" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = "~2.2.1"
numpy = "~1.26.4"
matplotlib = "~3.8.3"
scipy = "~1.12.0"
tensorflow = "~2.16.1"
scikit-learn = "~1.4.1.post1"
langchain = "~0.1.13"
huggingface-hub = "~0.22.1"
transformers = "~4.39.1"


[tool.poetry.group.dev.dependencies]
autopep8 = "~2.1.0"
pytest = "~8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
