# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: configmap-skabackend
data:
  THAPO_SKA_SECRET_FILE: /app/.secrets/.secret

---

# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: deployment-skabackend
  labels:
    app.kubernetes.io/name: deployment-skabackend
    app.kubernetes.io/component: skabackend
    app: skabackend
    environment: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deployment-skabackend
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      name: deployment-skabackend
      annotations:
      labels:
        app.kubernetes.io/name: deployment-skabackend
        app.kubernetes.io/component: skabackend
        app: skabackend
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: skabackend
          image: "{{ .Values.skabackend.image.registry }}/thapo_ska_backend:{{ .Values.skabackend.image.tag }}"
          imagePullPolicy: {{ .Values.skabackend.image.imagePullPolicy }}
          ports:
            - name: http-backend
              containerPort: {{ .Values.skabackend.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /backend
              port: http-backend
          readinessProbe:
            httpGet:
              path: /backend
              port: http-backend
          resources:
            limits:
              cpu: {{ .Values.skabackend.resources.limits.cpu }}
              memory: {{ .Values.skabackend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.skabackend.resources.requests.cpu }}
              memory: {{ .Values.skabackend.resources.requests.memory }}
          envFrom:
            - configMapRef:
                name: configmap-skabackend
          volumeMounts:
            - name: secret-backend-volume
              readOnly: true
              mountPath: "/app/.secrets"
            - name: skadata
              mountPath: {{ .Values.skabackend.volumeMounts.skadata.mountPath }}
      volumes:
        - name: secret-backend-volume
          secret:
            secretName: secret-backend
        - name: skadata
          persistentVolumeClaim:
            claimName: ska-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: service-skabackend
  labels:
    app.kubernetes.io/name: service-skabackend
    app.kubernetes.io/component: skabackend
    app: skabackend
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: deployment-skabackend
  ports:
    - port: {{ .Values.skabackend.port }}
      targetPort: http-backend
      protocol: TCP
      name: http-backend

---

{{- if .Values.skabackend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-skabackend
  labels:
    app.kubernetes.io/name: hpa-skabackend
    app.kubernetes.io/component: skabackend
    app: skabackend
    environment: {{ .Values.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-skabackend
  minReplicas: {{ .Values.skabackend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.skabackend.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.skabackend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.skabackend.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.skabackend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.skabackend.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
