# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: deployment-ska_backend
  labels:
    app.kubernetes.io/name: deployment-ska_backend
    app.kubernetes.io/component: ska_backend
    app: ska_backend
    environment: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deployment-ska_backend
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      name: deployment-ska_backend
      annotations:
      labels:
        app.kubernetes.io/name: deployment-ska_backend
        app.kubernetes.io/component: ska_backend
        app: ska_backend
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: ska_backend
          image: "{{ .Values.ska_backend.image.registry }}/thapo_ska_backend:{{ .Values.ska_backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.imagePullPolicy }}
          ports:
            - name: http-ska_backend
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /backend
              port: http-ska_backend
          readinessProbe:
            httpGet:
              path: /backend
              port: http-ska_backend
          resources:
            limits:
              cpu: {{ .Values.ska_backend.resources.limits.cpu }}
              memory: {{ .Values.ska_backend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.ska_backend.resources.requests.cpu }}
              memory: {{ .Values.ska_backend.resources.requests.memory }}
          volumeMounts:

---

apiVersion: v1
kind: Service
metadata:
  name: service-ska_backend
  labels:
    app.kubernetes.io/name: service-ska_backend
    app.kubernetes.io/component: ska_backend
    app: ska_backend
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: deployment-ska_backend
  ports:
    - port: {{ .Values.ska_backend.port }}
      targetPort: http-ska_backend
      protocol: TCP
      name: http-ska_backend

---

{{- if .Values.ska_backend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ska_backend
  labels:
    app.kubernetes.io/name: hpa-ska_backend
    app.kubernetes.io/component: ska_backend
    app: ska_backend
    environment: {{ .Values.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ska_backend
  minReplicas: {{ .Values.ska_backend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ska_backend.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ska_backend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ska_backend.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.ska_backend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ska_backend.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
