apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: thapo-ska-ingress
  labels:
    app.kubernetes.io/name: thapo-ska-ingress
    app.kubernetes.io/component: ingress
    app: ingress
    environment: {{ .Values.environment }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      # secretName: {{ .secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: service-ska_frontend
                port:
                  number: {{ .Values.ska_frontend.port }}
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: service-ska_backend
                port:
                  number: {{ .Values.ska_backend.port }}
