pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh "pwd"
                dir("devops/docker") {
                    sh "sudo docker compose -f docker-compose.yaml --env-file .env.dev build"
                }
            }
        }
        stage('push') {
            steps {
                dir("devops/docker") {
                    withCredentials([usernamePassword(credentialsId: 'registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh '''
                            sudo docker login -u "$USERNAME" -p "$PASSWORD" registry.thapo-dev.org:5000
                            sudo docker compose -f docker-compose.yaml --env-file .env.dev push
                        '''
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir("devops/docker") {
                    sh 'sudo docker compose -f docker-compose.yaml --env-file .env.dev up -d --remove-orphans --force-recreate --wait'
                }
            }
        }
    }
}