//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "thapo_ska_schema", table_name = "chat_message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub chat_message_id: i64,
    pub chat_id_fk: i64,
    pub message_type: String,
    pub message_body: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_chat::Entity",
        from = "Column::ChatIdFk",
        to = "super::user_chat::Column::ChatId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserChat,
}

impl Related<super::user_chat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserChat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
