//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::chat_message::Entity as ChatMessage;
pub use super::nn_model::Entity as NnModel;
pub use super::user_chat::Entity as UserChat;
pub use super::users::Entity as Users;
