//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

pub use super::nn_model::Entity as NnModel;
pub use super::user_chat_message::Entity as UserChatMessage;
pub use super::users::Entity as Users;
