namespace: thapo-ska-local
environment: local_kube

# FRONTEND
skafrontend:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-local_kube
    imagePullPolicy: IfNotPresent
  port: 14081

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# BACKEND
skabackend:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-local_kube
    imagePullPolicy: IfNotPresent
  port: 14082
  volumeMounts:
    skadata:
      mountPath: /home/thaposka/.config/ska/local_kube

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# IAM
skaiam:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-local_kube
    imagePullPolicy: IfNotPresent
  port: 14083

  resources:
    limits:
      cpu: 300m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi

# INGRESS
ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/app-root: /app
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  host: thapo-ska-local.thapo-local.org

# PV
pv:
  storage: 16Gi
  path: /var/lib/container-data/local-path-provisioner/thapo-ska/local
