namespace: thapo-ska-local
environment: local_kube

# FRONTEND
skafrontend:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-local_kube
    imagePullPolicy: IfNotPresent
  port: 14081

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# BACKEND
skabackend:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-local_kube
    imagePullPolicy: IfNotPresent
  port: 14082

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# IAM
skaiam:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-local_kube
    imagePullPolicy: IfNotPresent
  port: 14083

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

# INGRESS
ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/app-root: /app
  host: thapo-ska-local.thapo-local.org
