namespace: thapo-ska-prod
environment: prod

# FRONTEND
ska_frontend:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-prod
    imagePullPolicy: Always
  port: 14281

  resources:
    limits:
      cpu: 800m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# BACKEND
ska_backend:
  image:
    registry: registry.thapo-dev.org:5000/thapo
    tag: 0.1.1-prod
    imagePullPolicy: Always
  port: 14282

  resources:
    limits:
      cpu: 800m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 64Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# INGRESS
ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/app-root: /app
  host: thapo-ska.thapo.org
