pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                dir("devops/docker") {
                    sh "sudo docker compose -f docker-compose.yaml --env-file .env.prod build"
                }
            }
        }
        stage('push') {
            steps {
                dir("devops/docker") {
                    withCredentials([usernamePassword(credentialsId: 'registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh '''
                            sudo docker login -u "$USERNAME" -p "$PASSWORD" registry.thapo-dev.org:5000
                            sudo docker compose -f docker-compose.yaml --env-file .env.prod push
                        '''
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir("devops/kubernetes/thapo-ska") {
                    sh '''
                        sudo helm uninstall -n "thapo-ska-prod" "thapo-ska-prod" --ignore-not-found --wait
                        sudo helm install -f "values-prod.yaml" --create-namespace -n "thapo-ska-prod" "thapo-ska-prod" .
                    '''
                }
            }
        }
    }
}