FROM docker.io/rust:1.74.1
WORKDIR /app
RUN apt-get update && apt-get full-upgrade -y && apt-get install --no-install-recommends -y npm && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    npm install -g tailwindcss@3.3.6 && \
    rustup install nightly && \
    rustup default nightly && \
    rustup target add wasm32-unknown-unknown && \
    cargo install trunk