FROM docker.io/nginx:1.25.3
ARG ARG_THAPO_SKA_ENV_PROFILE
RUN apt-get update && apt-get clean && rm -rf /var/lib/apt/lists/*
ENV THAPO_SKA_ENV_FILE=/app/.env.${ARG_THAPO_SKA_ENV_PROFILE}
COPY ./ska_gateway/nginx/gateway-${ARG_THAPO_SKA_ENV_PROFILE}.conf /etc/nginx/conf.d/gateway-${ARG_THAPO_SKA_ENV_PROFILE}.conf
