FROM quay.io/keycloak/keycloak:23.0.4
ARG ARG_THAPO_SKA_ENV_PROFILE
ENV THAPO_SKA_SECRET_FILE=/opt/keycloak/.secret
COPY ./ska_iam/conf/${ARG_THAPO_SKA_ENV_PROFILE}/keycloak.conf /opt/keycloak/conf/keycloak.conf
COPY ./ska_iam/entrypoint.sh /opt/keycloak/entrypoint.sh
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/entrypoint.sh"]
CMD ["start"]